name = "frontend"
version = "0.1.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 4.6.3 and < 5.0.0"
lustre_http = ">= 0.6.0 and < 1.0.0"
modem = ">= 2.0.1 and < 3.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
decode = ">= 1.1.0 and < 2.0.0"
rada = ">= 0.5.0 and < 1.0.0"
envoy = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
